apiVersion: v1
kind: Secret
metadata:
  name: doctor-service-secret
type: Opaque
stringData:
  MONGO_URI: mongodb://mongo-service:27017/doctor_service_db
  JWT_SECRET: change_this_super_secret_key
  JWT_EXPIRES_IN: 1d
