apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: PirathapH/api-gateway:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/smartcarehub"
            - name: APPOINTMENT_SERVICE_URL
              value: "http://appointment-service:5001"
            - name: PAYMENT_SERVICE_URL
              value: "http://payment-service:5002"
            - name: PATIENT_SERVICE_URL
              value: "http://patient-service:5003"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
