apiVersion: v1
kind: Secret
metadata:
  name: smartcarehub-secrets
  namespace: smartcarehub
  labels:
    project: smartcarehub
type: Opaque
stringData:
  JWT_SECRET: "SmartCareHub_JWT_Secret_2026"
  AUTH_MONGO_URI: "mongodb://auth-db-service:27017/auth-service"
  PATIENT_MONGO_URI: "mongodb://patient-db-service:27017/patient-service"
